# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to include in the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow alembic to lowercase the
# case of table names when executing migrations
# (default is false)
# lowercase_table_names = false

# set to 'true' to allow alembic to detect
# multiple databases (default is false)
# multi_db = false

# logging configuration is defined at the bottom.
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/geo_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt = %H:%M:%S
